### ISSUE TITLE
Extend the Google Sheets plugin with tasks to create and delete spreadsheets and load data to a range

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-googleworkspace#117]
### Feature description

Add 3 new tasks to this plugin:
- [ ] `io.kestra.plugin.googleworkspace.sheets.Create` - this needs to output the `spreadsheetId` that has been created
- [ ] `io.kestra.plugin.googleworkspace.sheets.Delete `- delete a spreadsheet by `spreadsheetId`
- [ ] `io.kestra.plugin.googleworkspace.sheets.Load` - this can upload data to a given `spreadsheetId` with optional `range` selection 

The first two tasks are simple — the Load task should be similar to the [BigQuery Load task](https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.load#format) but with support for ION formatted data as well. This is possible as writing to a sheet requires writing data row by row (same as our usual ION format with one line per row), e.g.:

```bash
csv_content=$(cat data.csv | jq -R -s -c 'split("\n") | .[:-1] | map(split(","))')

curl -X PUT \
  "https://sheets.googleapis.com/v4/spreadsheets/YOUR_SPREADSHEET_ID/values/Sheet2!A1:append?valueInputOption=RAW" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"range\": \"Sheet2!A1\",
    \"majorDimension\": \"ROWS\",
    \"values\": $csv_content
  }"
```

best to use Google Java SDK instead of API directly, but just showing as an example.

## Task properties and usage

```yaml
id: myflow
namespace: company.team
description: |
  To connect to Google Sheets, follow these steps:
  - Enable Google Sheets API: If not done already, enable the Google Sheets API from the Google Cloud Console.
  - Create Service Account & Download the Key: Navigate to IAM & Admin → Service Accounts in Google Cloud Console.
  - Create a new service account and download the JSON key.
  - Share Sheet: Open the Google Sheet and share it with the client_email of the service account.✅
  https://docs.google.com/spreadsheets/d/1RPr1ilmYTTInyTXX8l-gCJXdBLftTArQ615oxqhT_iU/edit?gid=1750738117#gid=1750738117 

tasks:
  - id: create
    type: io.kestra.plugin.googleworkspace.sheets.CreateSpreadsheet
    serviceAccount: xxx
    description: https://developers.google.com/sheets/api/guides/create#java
    # output spreadsheetId 

  - id: load_data 
    description: |
      should work the same way as the BQ Load task but also support ION "format" for the "from" file 

      https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.load#format 

      the spreadsheets.values.update request seems correct https://developers.google.com/sheets/api/guides/values#java_2 
    type: io.kestra.plugin.googleworkspace.sheets.Load
    from: "{{ inputs.file }}"
    spreadsheetId: xxx
    range: Sheet2 # allow specifying a Sheet name or range as in https://kestra.io/plugins/plugin-googleworkspace/tasks/sheets/io.kestra.plugin.googleworkspace.sheets.readrange#range 
    serviceAccount: xxx
    format: CSV # we should support ION here as well
    csvOptions:
      fieldDelimiter: ";"

  - id: delete
    type: io.kestra.plugin.googleworkspace.sheets.DeleteSpreadsheet
    spreadsheetId:  1RPr1ilmYTTInyTXX8l-gCJXdBLftTArQ615oxqhT_iU
    serviceAccount: |
      {
        "type": "service_account",
        "project_id": "xxx",
        "private_key_id": "xxx",
        "private_key": "-----BEGIN PRIVATE KEY-----\n...
        "client_email": "spreadhseet-user@xxx.iam.gserviceaccount.com",
        ...
      }
```

**Comment by iNikitaGricenko** [comment]
For Load task
Correct me if i'm wrong: i should create methods that will also store/save data in file formats: Parquet, ORC, Avro, JSON, depending on which format selected by user? Same as in BigQuery Load task, in additional to CSV, ION

**Comment by anna-geller** [comment]
The user passes a file within the "`from`" property. Your task will need to:
- read it (for some formats, you may need to consider additional properties like csvOptions to know how to parse the data from the file) 
- load it within a selected range in the Google Sheet - if the user skips `range` or only specifies the sheet name like Sheet2, then load it with the header row (i.e. include column names)

Overall, you can check how the BQ Load task works and we'll need to replicate that behavior for Google Sheets — does it help? LMK if you need more clarification or examples, thx a lot!
